"""Data models for the Growspace Manager integration.

This package splits models into domain-specific sub-modules for maintainability.
All public types are re-exported here for backward-compatible imports.
"""

from custom_components.growspace_manager.const import PlantStage

from .base import BaseModel, BasePreset, _sanitize_numeric_fields
from .contract import GrowspaceCoordinatorData
from .genetics import PollinationEvent, SeedBatch
from .growspace import (
    ENVIRONMENT_FIELD_OWNERSHIP,
    ACInfinityDevice,
    ACInfinityGrowLight,
    CirculationFanConfig,
    DLIState,
    EnergyTracking,
    EnvironmentConfig,
    EnvironmentState,
    ExhaustFanConfig,
    FieldClass,
    FieldOwnership,
    GrowLightConfig,
    Growspace,
    GrowspaceEvent,
    GrowspaceType,
    SensorGroup,
    Subarea,
    VisionCheckupConfig,
    VisionCheckupResult,
    WaterUsageData,
)
from .ipm import IPMPreset, IPMPresetItem, IPMType
from .irrigation import (
    CropSteeringState,
    DrainConfig,
    DrainReading,
    ECRampCurve,
    ECRampPoint,
    ECTargetRange,
    IrrigationConfig,
    IrrigationStrategy,
    IrrigationTank,
    SubstrateEvent,
    SubstrateHistory,
    SubstrateProfile,
    TankWaterEvent,
    TankWaterHistory,
)
from .irrigation_recipe import (
    CropSteeringRecipe,
    IrrigationRecipe,
    RecipeProvenance,
    ScheduleRecipe,
)
from .nutrient import NutrientInventory, NutrientPreset, NutrientStock
from .plant import (
    DryingData,
    HarvestMetrics,
    MoistureEntry,
    PhenotypeScore,
    Plant,
    PlantGenetics,
    WeightEntry,
)
from .types import (
    DehumidifierRange,
    IPMPresetDict,
    IrrigationScheduleItem,
    NutrientEntry,
    NutrientPresetDict,
    NutrientPresetItem,
    PlantTimelineEvent,
    StageHistoryItem,
    TimelineEventMetadata,
)
from .vision_evidence import (
    AdmissionPhase,
    AnalysisState,
    BaselineBucket,
    BaselineMember,
    BaselineState,
    CaptureFileVariant,
    CaptureTrigger,
    ComparisonOutcome,
    ComparisonVerdict,
    EmbeddingSource,
    FileDeletionReason,
    FramingEpoch,
    FramingEpochReason,
    GrowRunRef,
    GrowRunRefSource,
    LabelKind,
    LightState,
    LightWindow,
    ObservationSource,
    VisionCapture,
    VisionCaptureFile,
    VisionEmbedding,
    VisionExplainerReport,
    VisionLabel,
    VisualComparisonResult,
)

# Explicit __all__ list for documentation and IDE support
__all__ = [
    "ENVIRONMENT_FIELD_OWNERSHIP",
    "ACInfinityDevice",
    "ACInfinityGrowLight",
    "AdmissionPhase",
    "AnalysisState",
    # base
    "BaseModel",
    "BasePreset",
    "BaselineBucket",
    "BaselineMember",
    "BaselineState",
    "CaptureFileVariant",
    "CaptureTrigger",
    "CirculationFanConfig",
    "ComparisonOutcome",
    "ComparisonVerdict",
    "CropSteeringRecipe",
    "CropSteeringState",
    "DLIState",
    "DehumidifierRange",
    "DrainConfig",
    "DrainReading",
    "DryingData",
    "ECRampCurve",
    "ECRampPoint",
    "ECTargetRange",
    "EmbeddingSource",
    "EnergyTracking",
    "EnvironmentConfig",
    "EnvironmentState",
    "ExhaustFanConfig",
    "FieldClass",
    "FieldOwnership",
    "FileDeletionReason",
    "FramingEpoch",
    "FramingEpochReason",
    "GrowLightConfig",
    "GrowRunRef",
    "GrowRunRefSource",
    "Growspace",
    # contract
    "GrowspaceCoordinatorData",
    "GrowspaceEvent",
    # growspace
    "GrowspaceType",
    "HarvestMetrics",
    "IPMPreset",
    "IPMPresetDict",
    "IPMPresetItem",
    # ipm
    "IPMType",
    "IrrigationConfig",
    # irrigation
    "IrrigationRecipe",
    # types
    "IrrigationScheduleItem",
    "IrrigationStrategy",
    "IrrigationTank",
    "LabelKind",
    "LightState",
    "LightWindow",
    "MoistureEntry",
    "NutrientEntry",
    "NutrientInventory",
    # nutrient
    "NutrientPreset",
    "NutrientPresetDict",
    "NutrientPresetItem",
    "NutrientStock",
    "ObservationSource",
    "PhenotypeScore",
    "Plant",
    # plant
    "PlantGenetics",
    "PlantStage",
    "PlantTimelineEvent",
    "PollinationEvent",
    "RecipeProvenance",
    "ScheduleRecipe",
    # genetics
    "SeedBatch",
    "SensorGroup",
    "StageHistoryItem",
    "Subarea",
    "SubstrateEvent",
    "SubstrateHistory",
    "SubstrateProfile",
    "TankWaterEvent",
    "TankWaterHistory",
    "TimelineEventMetadata",
    "VisionCapture",
    "VisionCaptureFile",
    "VisionCheckupConfig",
    "VisionCheckupResult",
    "VisionEmbedding",
    "VisionExplainerReport",
    "VisionLabel",
    "VisualComparisonResult",
    "WaterUsageData",
    "WeightEntry",
    "_sanitize_numeric_fields",
]
