"""Service schemas for Growspace Manager."""

from __future__ import annotations

from . import plant, strain_library, debug
from ..service_schemas import (
    ADD_GROWSPACE_SCHEMA,
    REMOVE_GROWSPACE_SCHEMA,
    ADD_PLANT_SCHEMA,
    UPDATE_PLANT_SCHEMA,
    REMOVE_PLANT_SCHEMA,
    MOVE_PLANT_SCHEMA,
    SWITCH_PLANT_SCHEMA,
    TRANSITION_PLANT_SCHEMA,
    MOVE_CLONE_SCHEMA,
    EXPORT_STRAIN_LIBRARY_SCHEMA,
    IMPORT_STRAIN_LIBRARY_SCHEMA,
    CLEAR_STRAIN_LIBRARY_SCHEMA,
    HARVEST_PLANT_SCHEMA,
    TAKE_CLONE_SCHEMA,
    DEBUG_CLEANUP_LEGACY_SCHEMA,
    DEBUG_LIST_GROWSPACES_SCHEMA,
    DEBUG_RESET_SPECIAL_GROWSPACES_SCHEMA,
    DEBUG_CONSOLIDATE_DUPLICATE_SPECIAL_SCHEMA,
)
