"""WebSocket API package for the Growspace Manager integration."""

from __future__ import annotations

import logging

from custom_components.growspace_manager.const import ATTR_NOTES, ATTR_PLANT_ID
from custom_components.growspace_manager.coordinator import GrowspaceCoordinator
from homeassistant.core import HomeAssistant, callback

from . import (
    ai_assistant,
    data,
    environment,
    genetics,
    irrigation,
    lineage,
    logbook,
    notifications,
    nutrients,
    plant,
    strain,
    subareas,
    timeline,
    vision,
)
from ._common import (
    _EPOCH_SENTINEL,
    _extract_ts,
    _merge_logbook_event,
    register_ws_command,
)
from .ai_assistant import (
    SCHEMA_WS_SEND_MESSAGE,
    SCHEMA_WS_START_CONVERSATION,
    WS_TYPE_SEND_MESSAGE,
    WS_TYPE_START_CONVERSATION,
    websocket_send_message,
    websocket_start_conversation,
)

# Re-export all handler functions so existing imports from `.websocket` still resolve
from .data import (
    SCHEMA_WS_GET_DATA,
    SCHEMA_WS_GET_GROW_REPORT,
    WS_TYPE_GET_DATA,
    WS_TYPE_GET_GROW_REPORT,
    websocket_get_growspace_data,
)
from .environment import (
    SCHEMA_WS_GET_HISTORY_STATS,
    SCHEMA_WS_UPDATE_SENSOR_COORDINATES,
    WS_TYPE_GET_HISTORY_STATS,
    WS_TYPE_UPDATE_SENSOR_COORDINATES,
    _downsample_entity_binary_search,
    _get_history_with_binary_search_downsample,
    _get_statistics_data,
    websocket_get_history_stats,
    websocket_update_sensor_coordinates,
)
from .genetics import (
    SCHEMA_WS_DELETE_BREEDER,
    SCHEMA_WS_GET_GENETICS_DATA,
    SCHEMA_WS_UPDATE_BREEDER,
    WS_TYPE_DELETE_BREEDER,
    WS_TYPE_GET_GENETICS_DATA,
    WS_TYPE_UPDATE_BREEDER,
    websocket_delete_breeder,
    websocket_get_genetics_data,
    websocket_update_breeder,
)
from .irrigation import (
    SCHEMA_WS_GET_IRRIGATION_ANALYTICS,
    WS_TYPE_GET_IRRIGATION_ANALYTICS,
    websocket_get_irrigation_analytics,
)
from .lineage import (
    SCHEMA_WS_GET_LINEAGE_TREE,
    SCHEMA_WS_GET_STRAIN_LINEAGE_TREE,
    SCHEMA_WS_IMPORT_STRAIN_LINEAGE_TREE,
    SCHEMA_WS_UPDATE_STRAIN_LINEAGE_TREE,
    WS_TYPE_GET_LINEAGE_TREE,
    WS_TYPE_GET_STRAIN_LINEAGE_TREE,
    WS_TYPE_IMPORT_STRAIN_LINEAGE_TREE,
    WS_TYPE_UPDATE_STRAIN_LINEAGE_TREE,
    websocket_get_lineage_tree,
    websocket_get_strain_lineage_tree,
    websocket_import_strain_lineage_tree,
    websocket_update_strain_lineage_tree,
)
from .logbook import (
    SCHEMA_WS_GET_ALERTS,
    SCHEMA_WS_GET_LOG,
    WS_TYPE_GET_ALERTS,
    WS_TYPE_GET_LOG,
    _query_logbook_events_impl,
    websocket_get_alerts,
    websocket_get_event_log,
)
from .nutrients import (
    SCHEMA_WS_GET_EC_RAMP_CURVES,
    SCHEMA_WS_GET_IPM_PRESETS,
    SCHEMA_WS_GET_NUTRIENT_INVENTORY,
    SCHEMA_WS_GET_NUTRIENT_PRESETS,
    SCHEMA_WS_REMOVE_NUTRIENT_STOCK,
    SCHEMA_WS_UPDATE_NUTRIENT_STOCK,
    WS_TYPE_GET_EC_RAMP_CURVES,
    WS_TYPE_GET_IPM_PRESETS,
    WS_TYPE_GET_NUTRIENT_INVENTORY,
    WS_TYPE_GET_NUTRIENT_PRESETS,
    WS_TYPE_REMOVE_NUTRIENT_STOCK,
    WS_TYPE_UPDATE_NUTRIENT_STOCK,
    websocket_get_ec_ramp_curves,
    websocket_get_ipm_presets,
    websocket_get_nutrient_inventory,
    websocket_get_nutrient_presets,
    websocket_remove_nutrient_stock,
    websocket_update_nutrient_stock,
)
from .strain import (
    SCHEMA_WS_DOWNLOAD_STRAIN_IMAGE,
    SCHEMA_WS_GET_EXTERNAL_STRAIN_DETAILS,
    SCHEMA_WS_GET_STRAIN_LIBRARY,
    SCHEMA_WS_QUERY_EXTERNAL_STRAIN,
    SCHEMA_WS_UPLOAD_STRAIN_IMAGE,
    WS_TYPE_DOWNLOAD_STRAIN_IMAGE,
    WS_TYPE_GET_EXTERNAL_STRAIN_DETAILS,
    WS_TYPE_GET_STRAIN_LIBRARY,
    WS_TYPE_QUERY_EXTERNAL_STRAIN,
    WS_TYPE_UPLOAD_STRAIN_IMAGE,
    websocket_download_strain_image,
    websocket_get_external_strain_details,
    websocket_get_strain_library,
    websocket_query_external_strain,
    websocket_upload_strain_image,
)
from .subareas import (
    SCHEMA_WS_ADD_SUBAREA,
    SCHEMA_WS_GET_SUBAREAS,
    SCHEMA_WS_REMOVE_SUBAREA,
    SCHEMA_WS_UPDATE_SUBAREA,
    WS_TYPE_ADD_SUBAREA,
    WS_TYPE_GET_SUBAREAS,
    WS_TYPE_REMOVE_SUBAREA,
    WS_TYPE_UPDATE_SUBAREA,
    websocket_add_subarea,
    websocket_get_subareas,
    websocket_remove_subarea,
    websocket_update_subarea,
)
from .timeline import (
    SCHEMA_WS_ADD_GROWSPACE_NOTE,
    SCHEMA_WS_ADD_TIMELINE_NOTE,
    SCHEMA_WS_REMOVE_TIMELINE_EVENT,
    WS_TYPE_ADD_GROWSPACE_NOTE,
    WS_TYPE_ADD_TIMELINE_NOTE,
    WS_TYPE_REMOVE_TIMELINE_EVENT,
    websocket_add_growspace_note,
    websocket_add_timeline_note,
    websocket_remove_timeline_event,
)
from .vision import (
    SCHEMA_WS_CAPTURE_SNAPSHOT,
    SCHEMA_WS_GET_SNAPSHOTS,
    SCHEMA_WS_GET_VISION_HISTORY,
    SCHEMA_WS_GET_VISION_HISTORY_V2,
    SCHEMA_WS_GET_VISION_STATUS,
    SCHEMA_WS_UPDATE_VISION_CHECKUP_CONFIG,
    WS_TYPE_CAPTURE_SNAPSHOT,
    WS_TYPE_GET_SNAPSHOTS,
    WS_TYPE_GET_VISION_HISTORY,
    WS_TYPE_GET_VISION_HISTORY_V2,
    WS_TYPE_GET_VISION_STATUS,
    WS_TYPE_UPDATE_VISION_CHECKUP_CONFIG,
    websocket_capture_snapshot,
    websocket_get_snapshots,
    websocket_get_vision_history,
    websocket_get_vision_history_v2,
    websocket_get_vision_status,
    websocket_update_vision_checkup_config,
)

_LOGGER = logging.getLogger(__name__)

_MODULES = [
    data,
    logbook,
    nutrients,
    plant,
    strain,
    lineage,
    timeline,
    genetics,
    environment,
    subareas,
    vision,
    irrigation,
    notifications,
    ai_assistant,
]


@callback
def async_register_websocket_api(hass: HomeAssistant) -> None:
    """Register all WebSocket API commands."""
    _LOGGER.debug("Registering WebSocket API for growspace_manager")

    for module in _MODULES:
        for command in module.COMMANDS:
            register_ws_command(hass, command)


__all__ = [
    "ATTR_NOTES",
    "ATTR_PLANT_ID",
    "SCHEMA_WS_ADD_GROWSPACE_NOTE",
    "SCHEMA_WS_ADD_SUBAREA",
    "SCHEMA_WS_ADD_TIMELINE_NOTE",
    "SCHEMA_WS_CAPTURE_SNAPSHOT",
    "SCHEMA_WS_DELETE_BREEDER",
    "SCHEMA_WS_DOWNLOAD_STRAIN_IMAGE",
    "SCHEMA_WS_GET_ALERTS",
    "SCHEMA_WS_GET_DATA",
    "SCHEMA_WS_GET_EC_RAMP_CURVES",
    "SCHEMA_WS_GET_EXTERNAL_STRAIN_DETAILS",
    "SCHEMA_WS_GET_GENETICS_DATA",
    "SCHEMA_WS_GET_GROW_REPORT",
    "SCHEMA_WS_GET_HISTORY_STATS",
    "SCHEMA_WS_GET_IPM_PRESETS",
    "SCHEMA_WS_GET_IRRIGATION_ANALYTICS",
    "SCHEMA_WS_GET_LINEAGE_TREE",
    "SCHEMA_WS_GET_LOG",
    "SCHEMA_WS_GET_NUTRIENT_INVENTORY",
    "SCHEMA_WS_GET_NUTRIENT_PRESETS",
    "SCHEMA_WS_GET_SNAPSHOTS",
    "SCHEMA_WS_GET_STRAIN_LIBRARY",
    "SCHEMA_WS_GET_STRAIN_LINEAGE_TREE",
    "SCHEMA_WS_GET_SUBAREAS",
    "SCHEMA_WS_GET_VISION_HISTORY",
    "SCHEMA_WS_GET_VISION_HISTORY_V2",
    "SCHEMA_WS_GET_VISION_STATUS",
    "SCHEMA_WS_IMPORT_STRAIN_LINEAGE_TREE",
    "SCHEMA_WS_QUERY_EXTERNAL_STRAIN",
    "SCHEMA_WS_REMOVE_NUTRIENT_STOCK",
    "SCHEMA_WS_REMOVE_SUBAREA",
    "SCHEMA_WS_REMOVE_TIMELINE_EVENT",
    "SCHEMA_WS_SEND_MESSAGE",
    "SCHEMA_WS_START_CONVERSATION",
    "SCHEMA_WS_UPDATE_BREEDER",
    "SCHEMA_WS_UPDATE_NUTRIENT_STOCK",
    "SCHEMA_WS_UPDATE_SENSOR_COORDINATES",
    "SCHEMA_WS_UPDATE_STRAIN_LINEAGE_TREE",
    "SCHEMA_WS_UPDATE_SUBAREA",
    "SCHEMA_WS_UPDATE_VISION_CHECKUP_CONFIG",
    "SCHEMA_WS_UPLOAD_STRAIN_IMAGE",
    "WS_TYPE_ADD_GROWSPACE_NOTE",
    "WS_TYPE_ADD_SUBAREA",
    "WS_TYPE_ADD_TIMELINE_NOTE",
    "WS_TYPE_CAPTURE_SNAPSHOT",
    "WS_TYPE_DELETE_BREEDER",
    "WS_TYPE_DOWNLOAD_STRAIN_IMAGE",
    "WS_TYPE_GET_ALERTS",
    "WS_TYPE_GET_DATA",
    "WS_TYPE_GET_EC_RAMP_CURVES",
    "WS_TYPE_GET_EXTERNAL_STRAIN_DETAILS",
    "WS_TYPE_GET_GENETICS_DATA",
    "WS_TYPE_GET_GROW_REPORT",
    "WS_TYPE_GET_HISTORY_STATS",
    "WS_TYPE_GET_IPM_PRESETS",
    "WS_TYPE_GET_IRRIGATION_ANALYTICS",
    "WS_TYPE_GET_LINEAGE_TREE",
    "WS_TYPE_GET_LOG",
    "WS_TYPE_GET_NUTRIENT_INVENTORY",
    "WS_TYPE_GET_NUTRIENT_PRESETS",
    "WS_TYPE_GET_SNAPSHOTS",
    "WS_TYPE_GET_STRAIN_LIBRARY",
    "WS_TYPE_GET_STRAIN_LINEAGE_TREE",
    "WS_TYPE_GET_SUBAREAS",
    "WS_TYPE_GET_VISION_HISTORY",
    "WS_TYPE_GET_VISION_HISTORY_V2",
    "WS_TYPE_GET_VISION_STATUS",
    "WS_TYPE_IMPORT_STRAIN_LINEAGE_TREE",
    "WS_TYPE_QUERY_EXTERNAL_STRAIN",
    "WS_TYPE_REMOVE_NUTRIENT_STOCK",
    "WS_TYPE_REMOVE_SUBAREA",
    "WS_TYPE_REMOVE_TIMELINE_EVENT",
    "WS_TYPE_SEND_MESSAGE",
    "WS_TYPE_START_CONVERSATION",
    "WS_TYPE_UPDATE_BREEDER",
    "WS_TYPE_UPDATE_NUTRIENT_STOCK",
    "WS_TYPE_UPDATE_SENSOR_COORDINATES",
    "WS_TYPE_UPDATE_STRAIN_LINEAGE_TREE",
    "WS_TYPE_UPDATE_SUBAREA",
    "WS_TYPE_UPDATE_VISION_CHECKUP_CONFIG",
    "WS_TYPE_UPLOAD_STRAIN_IMAGE",
    "_EPOCH_SENTINEL",
    "GrowspaceCoordinator",
    "_downsample_entity_binary_search",
    "_extract_ts",
    "_get_history_with_binary_search_downsample",
    "_get_statistics_data",
    "_merge_logbook_event",
    "_query_logbook_events_impl",
    "async_register_websocket_api",
    "websocket_add_growspace_note",
    "websocket_add_subarea",
    "websocket_add_timeline_note",
    "websocket_capture_snapshot",
    "websocket_delete_breeder",
    "websocket_download_strain_image",
    "websocket_get_alerts",
    "websocket_get_ec_ramp_curves",
    "websocket_get_event_log",
    "websocket_get_external_strain_details",
    "websocket_get_genetics_data",
    "websocket_get_growspace_data",
    "websocket_get_history_stats",
    "websocket_get_ipm_presets",
    "websocket_get_irrigation_analytics",
    "websocket_get_lineage_tree",
    "websocket_get_nutrient_inventory",
    "websocket_get_nutrient_presets",
    "websocket_get_snapshots",
    "websocket_get_strain_library",
    "websocket_get_strain_lineage_tree",
    "websocket_get_subareas",
    "websocket_get_vision_history",
    "websocket_get_vision_history_v2",
    "websocket_get_vision_status",
    "websocket_import_strain_lineage_tree",
    "websocket_query_external_strain",
    "websocket_remove_nutrient_stock",
    "websocket_remove_subarea",
    "websocket_remove_timeline_event",
    "websocket_send_message",
    "websocket_start_conversation",
    "websocket_update_breeder",
    "websocket_update_nutrient_stock",
    "websocket_update_sensor_coordinates",
    "websocket_update_strain_lineage_tree",
    "websocket_update_subarea",
    "websocket_update_vision_checkup_config",
    "websocket_upload_strain_image",
]
